config/routes.rb
Rails.application.routes.draw do
get 'my_cars/index'
root 'my_cars#index'
resources :my_cars
resources :rentals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_car.rb
class MyCar < ApplicationRecord
	has_many :Myrentals
end

app/models/myrental.rb
class Myrental < ApplicationRecord
	belongs_to :MyCar
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_cars_controller.rb
class MyCarsController < ApplicationController
	def index
		@my_cars= MyCar.all
	end
	def show
		@my_cars= MyCar.find(params[:id])
	end
	def new
		@my_cars= MyCar.new
	end

	def edit
		@my_cars= MyCar.find(params[:id])
	end
	
	def update
		car_attribute=params.require(:my_car).permit(:CarName , :CarType, :Year)
		@my_cars=  MyCar.find(params[:id])
#debugger
#logger.debug "Person attributes hash: #{@my_cars.attributes.inspect}"
#logger.info "Processing the request..."
		if @my_cars.update_attributes(car_attribute)
			redirect_to my_cars_path, :notice => "Car details saved"
		else
			render "index"
		end
	end

	def create
		car_attribute=params.require(:my_car).permit(:CarName , :CarType, :Year)
		@my_cars= MyCar.new(car_attribute)
#debugger
#logger.debug "Person attributes hash: #{@my_cars.attributes.inspect}"
#logger.info "Processing the request..."
		if @my_cars.save
			redirect_to my_cars_path, :notice => "A new car details saved"
		else
			render "new"
		end
	end

	def destroy
		@my_cars= MyCar.find(params[:id])

		if @my_cars.destroy
			redirect_to my_cars_path, :notice => "Car deleted"
		else
			render "index"
		end
	end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
	def index
		@my_car=MyCar.find(params[:id])

		@myrental= @my_car.Myrentals.build
		@myrentals= Myrental.all
	end
	def show
		@myrentals= MyRental.find(params[:id])
	end
	def new
		@myrentals= MyRental.new
	end

	def create
debugger
		@my_car=MyCar.find(params[:id])
		#@rental= @my_car.rentals.build(params[:rental])
		#rental_attribute=params.require(:rental).permit(:FromDate , :ToDate, :BorrowedBy, :my_cars_id)
		#@rentals= Rental.new(rental_attribute)

		#if @rentals.save
		#	redirect_to  rental_path, :id => @rentals[id]
		#else
		#	redirect_to  my_cars_path, :notice => "Could not save rental details"
		#	render "new"
		#end
	end


	def edit
		@myrentals= MyRental.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_car_helper.rb
module MyCarHelper
end

app/helpers/my_cars_helper.rb
module MyCarsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key,value|%>
	<p><%= value %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/my_cars/edit.html.erb
<h1>Edit <%= :CarType %> - <%= :CarName %> details</h1>

	<%= form_for @my_cars do |f| %>

	<p>	<%= f.label :CarName %> <%= f.text_field :CarName %></p>
	<p>	<%= f.label :CarType %> <%= f.text_field :CarType %></p>	
	<p>	<%= f.label :Year %> <%= f.text_field :Year %> </p>
	<%= f.submit "Submit" %>
	<% end %>

app/views/my_cars/index.html.erb
<h1>All my Cars</h1>

<table border=1>
  <tr>
	<th>Car Name</th>
	<th>Car Type</th>
	<th>Year</th>
	<th>Edit car details</th>
  </tr>

<% @my_cars.each do |car| %>
  <tr>
	<td><%= link_to car.CarName,:controller => :rentals , :action =>:index , :id => car.id %></td>
	<td><%=car.CarType %></td>
	<td><%=car.Year %></td>
	<td> <%= link_to "Edit",edit_my_car_path(car) %> </td>
	<td> <%= link_to "Delete",car, :data => {:confirm => "Are you sure you want to delete"} ,:method => :delete %> </td>
  </tr>
<% end %>

</table>


<p> <%= link_to "Add Car details", new_my_car_path %>  </p>

app/views/my_cars/new.html.erb
<h1>Add your new Car details</h1>

	<%= form_for @my_cars do |f| %>

	<p>	<%= f.label :CarName %> <%= f.text_field :CarName %></p>
	<p>	<%= f.label :CarType %> <%= f.text_field :CarType %></p>	
	<p>	<%= f.label :Year %> <%= f.text_field :Year %> </p>
	<%= f.submit "Submit" %>
	<% end %>

app/views/rentals/edit.html.erb
<h1>Rental details</h1>

	<%= form_for @rentals do |f| %>

	<p>	<%= f.label :CarName %> </p>
	<p>	Borrowed Date<%= f.text_field :FromDate %></p>	
	<p>	Returned Date<%= f.text_field :ToDate %> </p>	
	<p>	Borrowed By<%= f.text_field :BorrowedBy %> </p>
	<%= f.submit "Submit" %>
	<% end %>

app/views/rentals/index.html.erb
<h1>Rental details</h1>

	<%= form_for @myrental, :url => {:action => :create , :id => @myrental.my_car_id } do |f| %>

	<p>	Borrowed Date<%= f.text_field :FromDate %></p>	
	<p>	Returned Date<%= f.text_field :ToDate %> </p>	
	<p>	Borrowed By<%= f.text_field :BorrowedBy %> </p>
	<%= f.submit "Submit" %>
	<% end %>

<table border=1>
  <tr>
	<th>Borrowed Date</th>
	<th>Returned Date</th>
	<th>Borrowed By</th>
  </tr>

<% @myrentals.each do |r| %>
  <tr>
	<td><%=r.FromDate %></td>
	<td><%=r.ToDate %></td>
	<td><%=r.BorrowedBy %></td>
  </tr>
<% end %>

</table>